import XCTest
import CStemSeparator
@testable import MihoDesktop

final class SeparatedAudioTests: XCTestCase {
    func testNativeStatesAndSourceOrderMatchUpstreamPythonHostAndReset() throws {
        var error = [CChar](repeating: 0,count: 1024)
        let handle = try XCTUnwrap(miho_separator_create(SeparatedAudioAnalyzer.modelURL.path,&error,error.count),String(cString: error))
        defer { miho_separator_destroy(handle) }
        // Generated by the upstream streaming.py convenience host, ORT 1.26.0,
        // pinned teacher004 SHA. Independent host parity, not quality evidence.
        let golden: [[Float]] = [[-0.02552313,-0.015706163,-0.08358781,0.04087715],
                               [-0.000618255,-0.000748825,-0.003941827,0.001523949],
                               [-0.000756621,-0.003093048,-0.008239388,0.002254769]]
        for _ in 0..<2 {
            miho_separator_reset(handle)
            var vocal = [Float](repeating: 0,count: 128), drums = vocal, bass = vocal
            for hop in 0..<20 {
                var left = [Float](repeating: 0,count: 128), right = left
                for i in 0..<128 {
                    let t = Double(hop*128+i)
                    let l: Double = 0.15*sin(t*0.031)+0.07*sin(t*0.111)
                    let r: Double = 0.13*sin(t*0.029)+0.03*cos(t*0.073)
                    left[i] = Float(l); right[i] = Float(r)
                }
                let status = miho_separator_process(handle,&left,&right,&vocal,&drums,&bass)
                XCTAssertEqual(status,hop == 0 ? 2 : 1)
            }
            for (stem,values) in [vocal,drums,bass].enumerated() {
                for (index,sample) in [0,17,64,127].enumerated() {
                    XCTAssertEqual(values[sample],golden[stem][index],accuracy: 0.00002)
                }
            }
        }
    }
    func testResamplingSurvivesArbitraryCallbackBoundariesWithoutPitchShift() {
        for rate in [44_100.0,48_000.0,96_000.0] {
            let resampler = AnalysisResampler(sampleRate: rate)
            var output: [(Float,Float)] = []
            for i in 0..<Int(rate) {
                let l = Float(sin(2 * .pi*220*Double(i)/rate))
                resampler.consume(left: l,right: -l) { output.append(($0,$1)) }
            }
            XCTAssertEqual(output.count,44_100,accuracy: 1)
            for i in stride(from: 100,to: output.count,by: 71) {
                XCTAssertEqual(output[i].0,Float(sin(2 * .pi*220*Double(i)/44_100)),accuracy: 0.001)
                XCTAssertEqual(output[i].0,-output[i].1)
            }
        }
    }
    func testQueueOverflowDiscardsStaleResultsAndResetsModelBeforeLatestBlock() {
        let entered = expectation(description: "worker entered"), finished = expectation(description: "latest published")
        let gate = DispatchSemaphore(value: 0)
        var calls = 0, resets = 0, published: [Float] = []
        let pipeline = AudioAnalysisPipeline(sampleRate: 44_100,analyze: { stereo,_ in
            calls += 1
            if calls == 1 { entered.fulfill(); _ = gate.wait(timeout: .now()+3) }
            return SeparationResult()
        },reset: { resets += 1 },publish: { block,_ in
            published.append(block.stereo[0]); finished.fulfill()
        })
        func block(_ value: Float,_ frames: Int) -> AudioAnalysisPipeline.Block {
            .init(stereo: Array(repeating: value,count: frames*2),sensitivity: 1,deliveredAt: 0,hostTime: 0)
        }
        pipeline.enqueue(block(1,512))
        wait(for: [entered],timeout: 2)
        pipeline.enqueue(block(2,2000))
        pipeline.enqueue(block(3,4000)) // oversized callback is trimmed to bounded capacity
        gate.signal()
        wait(for: [finished],timeout: 3)
        pipeline.cancel()
        XCTAssertEqual(published,[3]); XCTAssertEqual(resets,1)
    }
    func testCancellationInvalidatesInFlightAnalysis() {
        let entered = expectation(description: "entered"), returned = expectation(description: "returned")
        let gate = DispatchSemaphore(value: 0)
        let noPublication = expectation(description: "cancelled result"); noPublication.isInverted = true
        let pipeline = AudioAnalysisPipeline(sampleRate: 44_100,analyze: { _,_ in
            entered.fulfill(); _ = gate.wait(timeout: .now()+3); returned.fulfill(); return SeparationResult()
        },reset: {},publish: { _,_ in noPublication.fulfill() })
        pipeline.enqueue(.init(stereo: [0,0],sensitivity: 1,deliveredAt: 0,hostTime: 0))
        wait(for: [entered],timeout: 2)
        pipeline.cancel(); gate.signal()
        wait(for: [returned,noPublication],timeout: 0.2)
    }
    func testIntegratedAnalyzerProducesFiniteFeaturesAtDeviceRate() throws {
        let analyzer = try SeparatedAudioAnalyzer(sampleRate: 48_000)
        let stereo: [Float] = (0..<1024).map { i in Float(0.1*sin(2 * .pi*220*Double(i/2)/48_000)) }
        let started = ProcessInfo.processInfo.systemUptime
        var result = SeparationResult()
        for _ in 0..<100 { result = analyzer.consume(stereo: stereo,sensitivity: 1) }
        let seconds = ProcessInfo.processInfo.systemUptime-started
        print("Separation + resampling + features: \(seconds) s for \(Double(51200)/48000) s audio")
        XCTAssertNil(result.error)
        XCTAssertTrue(seconds.isFinite) // Performance is reported separately; background load is not a unit-test invariant.
        XCTAssertTrue(result.rhythm.vocalPitch.isFinite)
    }
}
