#!/usr/bin/env python3
"""Developer-only BeatNet export. The app does not require Python/PyTorch.
Adapted architecture: Mojtaba Heydari, BeatNet, CC BY 4.0 (ThirdParty/).
Pinned checkpoint: 81cedd4beeb7235262db80969a0c9ce9a48a0ed4, model 2.
Usage: python scripts/export-beat-model.py path/to/model_2_weights.pt [2]
Requires torch, numpy, onnx, onnxruntime. No training or audio recording.
"""
import hashlib, pathlib, sys, json
import numpy as np
import torch
from torch import nn
import onnxruntime as ort

ROOT = pathlib.Path(__file__).resolve().parents[1]
CHECKPOINT_SHAS = {'1':'619091bc317ca3e83b45591d46f6de3d5a41588bcb39fe9fe7be30cffa6aca84', '2':'5878a18c079fa0b0139879b14ed2b5b7595faef8c3d16210aed141fd00fa2d58'}

class StreamingBeatNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv1d(1, 2, 10)
        self.linear0 = nn.Linear(262, 150)
        self.lstm = nn.LSTM(150, 150, num_layers=2, batch_first=True)
        self.linear = nn.Linear(150, 3)
    def forward(self, features, hidden, cell):
        x = torch.nn.functional.max_pool1d(torch.relu(self.conv1(features.reshape(1, 1, 272))), 2)
        x = self.linear0(x.reshape(1, 262)).reshape(1, 1, 150)
        x, (h, c) = self.lstm(x, (hidden, cell))
        probabilities = torch.softmax(self.linear(x).reshape(3), dim=0)
        return probabilities, h, c

def filterbank():
    # BeatNet/madmom training convention: the odd 1411-point FFT returns
    # 705 bins; frequency labels use 2*705, deliberately preserving that
    # convention rather than substituting a mel or 2048-bin spectrogram.
    freqs = 440 * 2**(np.arange(np.floor(np.log2(30/440)*24), np.ceil(np.log2(17000/440)*24))/24)
    freqs = freqs[(freqs >= 30) & (freqs <= 17000)]
    hz = np.arange(705)*22050/1410
    indices = np.clip(np.searchsorted(hz, freqs), 1, 704)
    indices -= freqs-hz[indices-1] < hz[indices]-freqs
    bins = np.unique(indices)
    filters = []
    for start, center, stop in zip(bins[:-2], bins[1:-1], bins[2:]):
        weights = np.r_[np.linspace(0, 1, center-start, endpoint=False), np.linspace(1, 0, stop-center, endpoint=False)].astype(np.float32)
        weights /= weights.sum()
        filters.append((int(start), weights))
    assert len(filters) == 136
    return filters

def features(window, previous, filters):
    spectrum = np.abs(np.fft.rfft(window*np.hanning(1411)).astype(np.complex64))[:705]
    log = np.array([np.log10(1+np.dot(spectrum[start:start+len(w)], w)) for start,w in filters], dtype=np.float32)
    diff = np.maximum(0, log-previous) if previous is not None else np.zeros(136, dtype=np.float32)
    return np.r_[log, diff].astype(np.float32), log

def test_window(frame):
    # Deterministic, repository-owned synthetic fixture; no song samples.
    t = (np.arange(1411)+frame*441)/22050
    return ((.16+.08*np.sin(t*7))*np.sin(2*np.pi*330*t)+.09*np.sin(2*np.pi*123*t)+.025*np.cos(2*np.pi*3400*t)).astype(np.float32)

def main():
    checkpoint = pathlib.Path(sys.argv[1])
    assert hashlib.sha256(checkpoint.read_bytes()).hexdigest() == CHECKPOINT_SHAS[sys.argv[2] if len(sys.argv) > 2 else '2']
    torch.set_num_threads(1)
    torch.manual_seed(0)
    model = StreamingBeatNet().eval()
    model.load_state_dict(torch.load(checkpoint, map_location='cpu', weights_only=True))
    target = ROOT/'Resources/Models/beatnet.onnx'
    h = torch.zeros(2, 1, 150); c = h.clone()
    torch.onnx.export(model, (torch.zeros(1, 1, 272), h, c), target,
                      input_names=['features','hidden','cell'], output_names=['probabilities','next_hidden','next_cell'],
                      opset_version=17, dynamo=False)
    session = ort.InferenceSession(str(target), providers=['CPUExecutionProvider'])
    filters = filterbank()
    header = ['// Generated by scripts/export-beat-model.py. BeatNet log-frequency filters.', '#pragma once', 'struct BeatFilter { int start, count; const float *weights; };']
    for i,(_,w) in enumerate(filters):
        header.append('static const float beatWeights%d[] = {%s};' % (i, ','.join(format(float(x),'.9e')+'f' for x in w)))
    header.append('static const BeatFilter beatFilters[136] = {')
    header.extend('{%d,%d,beatWeights%d},' % (s,len(w),i) for i,(s,w) in enumerate(filters))
    header.append('};')
    (ROOT/'Sources/CStemSeparator/BeatFilters.h').write_text('\n'.join(header)+'\n')
    previous = None; oh = h.numpy(); oc = c.numpy(); golden = []
    with torch.inference_mode():
        for i in range(30):
            f, previous = features(test_window(i), previous, filters)
            p,h,c = model(torch.from_numpy(f.reshape(1,1,272)), h,c)
            op,oh,oc = session.run(None, {'features':f.reshape(1,1,272),'hidden':oh,'cell':oc})
            assert np.max(np.abs(op-p.numpy())) < 2e-6
            golden.append({'probabilities':op.tolist(),'features':f.tolist() if i in [0,1,10,29] else []})
    (ROOT/'Tests/MihoDesktopTests/Fixtures/beatnet-golden.json').write_text(json.dumps(golden))
    print('Model SHA256:',hashlib.sha256(target.read_bytes()).hexdigest(), 'size:',target.stat().st_size)
    print('Torch/ONNX parity: 30 recurrent frames < 2e-6; filters:', len(filters))

if __name__ == '__main__': main()
